### ISSUE TITLE
提示：Cannot load library 

### ISSUE THREAD

**Issue by kwan3277** [xuncv/opencv_aardio#1]
已下载DLL放置在\lib\cv2\.res，运行时提示：
---------------------------
aardio：运行时错误
---------------------------
文件:[string "import cv2..."]
错误行号:#1
错误:import cv2 failed :

文件:...esktop\opencv_aardio-main\lib\cv2\_.aardio
错误行号:#2
错误:Cannot load library '~/lib/cv2/.res/OpenCvSharpExtern.dll'.
---------------------------------------------------
调用栈:
	[kernel]: in function 'import'
	[string "import cv2..."]:1: in main chunk
---------------------------
确定   
---------------------------

是不是因为DLL文件下载的不对？系统win10x64

**Comment by xuncv** [comment]
看提示应该是位置不对. csharp的那个项目是需要修改的,不修改的话,aardio调用比较复杂.
我改过的dll已经放到本项目的releases目录下, https://github.com/xuncv/opencv_aardio/releases
源码需改动的地方挺多的,只能慢慢改,具体细节可以关注commit日志

**Comment by kwan3277** [comment]
按您的方法解决了。
