### ISSUE TITLE
inRange方法没有实现吗？

### ISSUE THREAD

**Issue by wslgy** [xuncv/opencv_aardio#3]
你好，我最近用您的库做个照片换底色的工具，照着网上python例子写的，发现没有inRange方法，自己照你其他方法写了个方法出了点问题

**Comment by xuncv** [comment]
已经实现. 需同时修改dll源码. 请到https://github.com/xuncv/opencv-plugin/releases 下载最新dll.
inRange范例在 test\inRange.aardio

**Comment by wslgy** [comment]
谢谢大佬
