### ISSUE TITLE
“下载最新dll文件,复制到/lib/cv2/.res/中”的.res文件夹问题

### ISSUE THREAD

**Issue by zhhl99** [xuncv/opencv_aardio#4]
我在/lib/cv2/下没找到.res文件夹，自己创建一个吧，也无法创建（win7系统），不知道是不是方法不对
最后创建了一个res文件夹，没有前面的点，然后把下载的DLL文件放进去。
运行demo提示错误，最后把_.aardio里面的“.res”替换称"res"解决的

**Comment by xuncv** [comment]
.res是为了让ide和github忽略掉这个目录.我在win10下是可以创建的.win7在我印象中貌似不能直接创建. 可以用代码创建.
`import fsys
fsys.createDir("/lib/cv2/.res")`
库封装到正式版时,会发布成扩展库,就可以ide内安装了

**Comment by kwan3277** [comment]
这个问题遇到过，家里的一台Win10可创建.res文件家，但另一台和单位的Win10就不行，提示“必须输入文件名”，一台复制aardio文件夹Lib里的.res目录复制过去，另一台用新建bat用批处理建立的文件夹。md .res 就行
需要注意，放DLL路径里有中文也会提示错误。

**Comment by aardio** [comment]
1、在 aardio 里右键点击库名称，
2、在弹出菜单里点击「创建目录」
3、目录名称输入 .res

**Comment by zhhl99** [comment]
> 1、在 aardio 里右键点击库名称，
> 2、在弹出菜单里点击「创建目录」
> 3、目录名称输入 .res

这个还是很方便的
