### ISSUE TITLE
CV2默认库里的bitwise_or，bitwise_xor函数是否有个小BUG？

### ISSUE THREAD

**Issue by zhhl99** [xuncv/opencv_aardio#5]
`bitwise_or = function(src1,src2,mask){
    var dst = ..cv2.mat();
    mask = mask ? (mask.cvPtr)
	var err = dll.core_bitwise_or(src1.cvPtr,src2.cvPtr.dst.cvPtr,null);  //这里是否应该为：src2.cvPtr,dst.cvPtr,null
	return dst; 
}

bitwise_xor = function(src1,src2,mask){
    var dst = ..cv2.mat();
    mask = mask ? (mask.cvPtr)
	var err = dll.core_bitwise_xor(src.cvPtr,src2.cvPtr,dst.cvPtr,null)  //这里是否应该为src1.cvPtr,src2.cvPtr,dst.cvPtr,null
	return dst; 
}`

改后调用正常，没改前总报错

**Comment by xuncv** [comment]
已修复 感谢
