### ISSUE TITLE
请教findContours返回的hierarchy的用法？

### ISSUE THREAD

**Issue by ghoukhj** [xuncv/opencv_aardio#6]
https://blog.csdn.net/weixin_44791964/article/details/101477630
这篇文章当中有
hierarchy是轮廓之间的关系，其变量类型为vector，每一个hierarchy的元素包括了四个int的数据，分别表示第i个轮廓的后一个轮廓、前一个轮廓、子轮廓、父轮廓的索引编号
在aardio当中没发现hierarchy的用法，能否给予提示？
谢谢

**Comment by ghoukhj** [comment]
感谢回复
我是不懂得在aardio里hierarchy怎么用，看csdn文章它是包含父子轮廓关系的数组

**Comment by xuncv** [comment]
findContours 在aardio中有很多重载。我采用了比较简单和常用的api。hierarchy 只有在需要轮廓父子关系的时候才用，其增益效果远没有图像预处理后来的多。aardio中返回的是hierarchy 是一个Mat对象，其解析意义并不大

**Comment by ghoukhj** [comment]
感谢回复
那如果在aardio里用findContours后，需要获取父子轮廓关系的话应该怎么实现？
https://blog.csdn.net/weixin_44791964/article/details/101477630
就像这篇文章里说的hierarchy一样
