### ISSUE TITLE
下载后提未错误putTextZH为NULL

### ISSUE THREAD

**Issue by kwan3277** [xuncv/opencv_aardio#7]
---------------------------
aardio：运行时错误
---------------------------
错误行号:#4
文件:[string "import cv2..."]:
不支持此操作:call
定义类型:method(table)
名字:'putTextZH'
类型:null
---------------------------------------------------
调用栈:
	[string "import cv2..."]:4: in main chunk
---------------------------
确定   
---------------------------

**Comment by xuncv** [comment]
需更新dll https://github.com/xuncv/opencv-plugin/releases

**Comment by kwan3277** [comment]
已经下载最新的放到\opencv_aardio-main\lib\cv2\.res中了。
